### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by Nicte** [billyvg/pokemon-journal#7] opened 2016-07-27 17:40 UTC
There seems to be some issue with the sorting algorithm:

![image](https://cloud.githubusercontent.com/assets/4835465/17185591/f6ac3dde-5431-11e6-9145-5b1d7a4eb1cf.png)

**Comment by onilton** [comment] 2016-08-11 20:44
This seems like a duplicate of https://github.com/billyvg/pokemon-journal/issues/6 and kind of fixed in https://github.com/billyvg/pokemon-journal/pull/17

**Comment by billyvg** [comment] 2016-08-12 00:56
Yep, this should be fixed in #17

**Closed as completed by billyvg** 2016-08-12 00:56 UTC
Labels: bug
